### PR TITLE
Testing with pytorch version 1

### PR DESCRIPTION
**Pull request by InnocentBug**

### CODE REVIEW

**Comment by InnocentBug** [comment]
I set up conda environment files with a pinned pytorch version of 1.13.1.
But I hide those from the users, since they should be only used for testing.

**Comment by InnocentBug** [comment]
At the moment this approach does not work with GPU.
Since it creates a mismatch in CUDA versions.

Is it ok to only test the old pytorch version on the CPU?

**Comment by InnocentBug** [comment]
This PR include #18 merge that one first.

**Comment by InnocentBug** [comment]
> At the moment this approach does not work with GPU. Since it creates a mismatch in CUDA versions.
> 
> Is it ok to only test the old pytorch version on the CPU?

If yes, I can remove that test.

**Comment by risi-kondor** [comment]
Yes, it is fine to only test running on Python 1.13 on the CPU. Thanks!

**Pull request merged**
