### PR TITLE
More comprehensive testing of gather with ptensorlayer

### PR DESCRIPTION
**Pull request by InnocentBug**
I try a variety of graphs and atomspacks from subgraphs to test this out.

Turns out.
Only simple atomspacks work so far.
But this a few bugfixes and improvements that are worth merging in.

New included:

1.  Comparison between graphs on the python side
2. Bugfix for viewing graphs with no edges.

### CODE REVIEW

**Comment by InnocentBug** [comment]
For this here all tests are green, but there are cases that are not green.

When I calcualte the loss as gather + L1Loss and atomspacks have more then one member.
The jacobian matrix in gradcheck fails.

Here is an example of a graph and atomspack:
```
G = Ggraph on 10 vertices:
  [ 0 1 1 1 1 1 1 1 1 1 ]
  [ 1 0 1 1 1 1 1 1 1 1 ]
  [ 1 1 0 1 1 1 1 1 1 1 ]
  [ 1 1 1 0 1 1 1... 1 0 1 1 1 1 ]
  [ 1 1 1 1 1 1 0 1 1 1 ]
  [ 1 1 1 1 1 1 1 0 1 1 ]
  [ 1 1 1 1 1 1 1 1 0 1 ]
  [ 1 1 1 1 1 1 1 1 1 0 ]

atoms = ([0,9,8],[0,9,7],[0,9,6],[0,9,5],[0,9,4],[0,9,3],[0,9,2],[0,9,1],[0,8,7],[0,8,6],[0,8,5],[0,8,4],[0,8,3],[0,8,2],[0,8,...4,8,6],[4,8,5],[4,7,6],[4,7,5],[4,6,5],[5,9,8],[5,9,7],[5,9,6],[5,8,7],[5,8,6],[5,7,6],[6,9,8],[6,9,7],[6,8,7],[7,9,8]), nc = 2, device = 'cpu'
```

And the gradient is simply 0 everywhere, when it should be non-zero.

**Review by risi-kondor — COMMENTED** [review]
Why was the N>0 condition needed in GgraphObj::edge_list? What was the symptom and did this solve the problem? I looked at the code and don't immediately see why anything pathological would happen for graphs with no edges here.

**Comment by InnocentBug** [comment]
> Why was the N>0 condition needed in GgraphObj::edge_list? What was the symptom and did this solve the problem? I looked at the code and don't immediately see why anything pathological would happen for graphs with no edges here.

Here is how you can trigger the problem:
```
ptens) 08:05 ptens@dewig 221$ python
Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ptens
Starting cnine tensor library without CUDA support...
Starting ptens...
>>> import torch
>>> g = ptens.ggraph.from_edge_index(torch.Tensor([[0], [0]]).int())
>>> g.cache(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ludwig/miniconda3/envs/ptens/lib/python3.12/site-packages/ptens/ggraph.py", line 86, in cache
    self.obj.cache(key)
IndexError: cnine::TYPE cnine::TensorView<TYPE>::set(int, int, TYPE) const [with TYPE = int] index (0,0) out of range of (2,0)
>>> 
```

**Comment by InnocentBug** [comment]
Actually, I found a different problem that allowed me to roll this back.

Do you not allow self-edges in graphs?

For now, I implemented using a safety guard against self-edges and that works too.

Is that correct?
Self-edges are not allowed at the moment?

**Pull request merged**
